ALTER TABLE public.players DROP COLUMN IF EXISTS physique;
ALTER TABLE public.players DROP COLUMN IF EXISTS agility;
ALTER TABLE public.players DROP COLUMN IF EXISTS magic_power;
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS dexterity INTEGER NOT NULL DEFAULT 10;
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS constitution INTEGER NOT NULL DEFAULT 10;
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS intelligence INTEGER NOT NULL DEFAULT 10;
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS wisdom INTEGER NOT NULL DEFAULT 10;
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS charisma INTEGER NOT NULL DEFAULT 10;
